
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.HEIGHT;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hasil
 */
public class Acceptor extends javax.swing.JDialog {

    String bg;
    String id;

    /**
     * Creates new form Acceptor
     */
    public Acceptor(String a, String id) {
        initComponents();
        bg = a;
        this.id = id;
        this.setLocationRelativeTo(null);
        this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Last_Name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Last_Name1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        First_Name1 = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        Phone_No = new javax.swing.JLabel();
        Address1 = new javax.swing.JTextField();
        Phone_No1 = new javax.swing.JTextField();
        Description = new javax.swing.JLabel();
        Description1 = new javax.swing.JTextField();
        First_Name = new javax.swing.JLabel();

        setTitle("Acceptor Information");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255)), "Acceptor Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 204, 51))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        Last_Name.setText("Last Name");

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Address.setText("Address");

        Phone_No.setText("Phone No.");

        Phone_No1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone_No1ActionPerformed(evt);
            }
        });

        Description.setText("Description");

        Description1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Description1ActionPerformed(evt);
            }
        });

        First_Name.setText("First Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Description1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Last_Name)
                                    .addComponent(Phone_No)
                                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(First_Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Phone_No1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(First_Name1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(Last_Name1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Address1, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(0, 156, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Last_Name)
                    .addComponent(Last_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone_No1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone_No))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (IsValidData()) {
            try {
                ArrayList data = this.getDataToSave();
                db_Operation1 db = new db_Operation1();
                db.addAcceptorInformtaion(data);
                db.removeDonor(id);
                JOptionPane.showMessageDialog(this, "Acceptor added successfully");
                this.dispose();
            } catch (ParseException ex) {
                System.out.println("Error in Parse during add Donor");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Phone_No1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone_No1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone_No1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();         // TODO add your handling code here:
        new main_class().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Description1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Description1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Description1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        // Move the window
        this.setLocation(x, y);

    }//GEN-LAST:event_formWindowOpened

    public ArrayList getDataToSave() {
        ArrayList data = new ArrayList();
        data.add(this.First_Name1.getText());
        data.add(this.Last_Name1.getText());
        data.add(this.Phone_No1.getText());

        data.add(this.Address1.getText());
        data.add(bg);
        data.add(this.Description1.getText());

//    if(RadioFemale.isSelected())
//        data.add("Female");
//    else
//        data.add("Male");
//     
        return data;

    }

    public boolean isNumeric(String a) {
        return a.matches("-?\\d+(\\.\\d+)?");
    }

    public boolean isAlphabet(String name) {
        return name.matches("[a-zA-Z]+");
    }

    public boolean IsValidData() {
        boolean result = true;
        if (this.First_Name1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the First Name", "Error", HEIGHT);
            result = false;// TODO add your handling code here:
        } else if (!isAlphabet(this.First_Name1.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid first name", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if (this.Last_Name1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the last Name", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if (!isAlphabet(this.Last_Name1.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid last name", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if (this.Address1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the address", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if (!isAlphabet(this.Address1.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Address", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if (this.Phone_No1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the Phone no", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if (!isNumeric(this.Phone_No1.getText())) {
            JOptionPane.showMessageDialog(this, "Invalid Phone Number", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if (this.Description1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the description", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else {
        }
        return result;

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField Address1;
    private javax.swing.JLabel Description;
    private javax.swing.JTextField Description1;
    private javax.swing.JLabel First_Name;
    private javax.swing.JTextField First_Name1;
    private javax.swing.JLabel Last_Name;
    private javax.swing.JTextField Last_Name1;
    private javax.swing.JLabel Phone_No;
    private javax.swing.JTextField Phone_No1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
