
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hasil
 */
public class main_class extends javax.swing.JFrame {

    /**
     * Creates new form main_class
     */
    public main_class() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jAdd = new javax.swing.JMenu();
        IAdd = new javax.swing.JMenuItem();
        jView = new javax.swing.JMenu();
        IView = new javax.swing.JMenuItem();
        jsearch = new javax.swing.JMenu();
        Isearch = new javax.swing.JMenuItem();
        jacceptor = new javax.swing.JMenu();
        Iacceptor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Donor Management Sytem");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\5th sem\\simulation_lab\\Donar_Management_System\\image\\donoation_pic.jpg")); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButton1.setMinimumSize(new java.awt.Dimension(500, 500));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jAdd.setText("Donor");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        IAdd.setText("Add Donor");
        IAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IAddActionPerformed(evt);
            }
        });
        jAdd.add(IAdd);

        jMenuBar1.add(jAdd);

        jView.setText("View");

        IView.setText("View Donors");
        IView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IViewActionPerformed(evt);
            }
        });
        jView.add(IView);

        jMenuBar1.add(jView);

        jsearch.setText("Search");
        jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchActionPerformed(evt);
            }
        });

        Isearch.setText("Search Blood");
        Isearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsearchActionPerformed(evt);
            }
        });
        jsearch.add(Isearch);

        jMenuBar1.add(jsearch);

        jacceptor.setText("Acceptor ");
        jacceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jacceptorActionPerformed(evt);
            }
        });

        Iacceptor.setText("Acceptor Info");
        Iacceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IacceptorActionPerformed(evt);
            }
        });
        jacceptor.add(Iacceptor);

        jMenuBar1.add(jacceptor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IViewActionPerformed
        // TODO add your handling code here
        this.dispose();
        View v1 = new View(new javax.swing.JFrame(), true);
        v1.setVisible(true);
    }//GEN-LAST:event_IViewActionPerformed

    private void jsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jsearchActionPerformed

    private void IsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsearchActionPerformed
        // TODO add your handling code here:
//           this.dispose();
        Search s1 = new Search();
        s1.setVisible(true);
    }//GEN-LAST:event_IsearchActionPerformed

    private void jacceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jacceptorActionPerformed
        // TODO add your handling code here

    }//GEN-LAST:event_jacceptorActionPerformed

    private void IacceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IacceptorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewAcceptor v1 = new ViewAcceptor();
        v1.setVisible(true);
    }//GEN-LAST:event_IacceptorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        // Move the window
        this.setLocation(x, y);

    }//GEN-LAST:event_formWindowOpened

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddActionPerformed

    private void IAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IAddActionPerformed
        // TODO add your handling code here:
        SignUp si = new SignUp();
        si.setVisible(true);
    }//GEN-LAST:event_IAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_class.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_class().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IAdd;
    private javax.swing.JMenuItem IView;
    private javax.swing.JMenuItem Iacceptor;
    private javax.swing.JMenuItem Isearch;
    private javax.swing.JMenu jAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jView;
    private javax.swing.JMenu jacceptor;
    private javax.swing.JMenu jsearch;
    // End of variables declaration//GEN-END:variables
}
