
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hasil
 */
public class update extends javax.swing.JDialog {

    String ID;
       public update(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public update(String id) {
        initComponents();
          this.setLocationRelativeTo(null);
      this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        this.ID = id;
        this.setVisible(true);
    }

  
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        other = new javax.swing.JPanel();
        Last_Name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Start_Time = new javax.swing.JLabel();
        bg = new javax.swing.JComboBox<>();
        End_Time = new javax.swing.JLabel();
        Last_Name1 = new javax.swing.JTextField();
        First_Name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        wt = new javax.swing.JTextField();
        First_Name1 = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        Blood_Group = new javax.swing.JLabel();
        Phone_No = new javax.swing.JLabel();
        Phone1 = new javax.swing.JTextField();
        Address1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Age1 = new javax.swing.JTextPane();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setTitle("Update");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        other.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 255)), "Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 204, 51))); // NOI18N

        Last_Name.setText("Last Name");

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Start_Time.setText("Gender");

        bg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgActionPerformed(evt);
            }
        });

        End_Time.setText("Weight");

        First_Name.setText("First Name");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        wt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wtActionPerformed(evt);
            }
        });

        Address.setText("Address");

        Blood_Group.setText("Blood Group");

        Phone_No.setText("Phone No.");

        Address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Age");

        jScrollPane1.setViewportView(Age1);

        male.setText("Male");

        female.setText("Female");

        javax.swing.GroupLayout otherLayout = new javax.swing.GroupLayout(other);
        other.setLayout(otherLayout);
        otherLayout.setHorizontalGroup(
            otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(otherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Last_Name)
                        .addComponent(Blood_Group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(First_Name)
                        .addComponent(Phone_No)
                        .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Start_Time)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(End_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address1)
                    .addComponent(First_Name1)
                    .addComponent(Last_Name1)
                    .addComponent(Phone1)
                    .addComponent(jScrollPane1)
                    .addGroup(otherLayout.createSequentialGroup()
                        .addComponent(male)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(female))
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        otherLayout.setVerticalGroup(
            otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherLayout.createSequentialGroup()
                        .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(First_Name)
                            .addComponent(First_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Last_Name)
                            .addComponent(Last_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Phone_No))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(otherLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Start_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(otherLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(male)
                                    .addComponent(female))
                                .addGap(8, 8, 8)))
                        .addGap(18, 18, 18)
                        .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Blood_Group, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(End_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(otherLayout.createSequentialGroup()
                        .addComponent(wt, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(otherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        // Move the window
        this.setLocation(x, y);
        try {
       
                    
            db_operation dbopt = new db_operation();
            ResultSet rs = dbopt.viewSingleDonorInformation(ID);
            if(rs.next()){
                this.First_Name1.setText(rs.getString("first_name"));
                this.Last_Name1.setText(rs.getString("last_name"));
                this.Address1.setText(rs.getString("address"));
                this.Phone1.setText(rs.getString("phone_no"));
                this.Age1.setText(rs.getString("age"));
                //this.gender.setText(rs.getString("state"));
                String gen = rs.getString("gender");
                if(gen.equals("Male"))
                    this.male.setSelected(true);
                else
                    this.female.setSelected(true);
                
               this.bg.setSelectedItem(rs.getString("blood_group"));
                this.wt.setText(rs.getString("weight"));
                
                
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void Address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Address1ActionPerformed

    private void wtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new main_class().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bgActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (isValidData()) {
           
                ArrayList data = getDataToSave();
                db_operation db = new db_operation();
                db.UpdateDatatoStudentTable(data,Integer.parseInt(ID));
                //JOptionPane.showMessageDialog(this, "Donor added successfully");
                this.dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public ArrayList getDataToSave() {
        ArrayList data = new ArrayList();
        data.add(this.First_Name1.getText());
        data.add(this.Last_Name1.getText());
        data.add(this.Address1.getText());
        String i=(this.Phone1.getText());
        int j=i.length();
        if (j>10)
        {
            JOptionPane.showMessageDialog(this, "Invalid Phone", "Error", HEIGHT);
        }
        data.add(this.Phone1.getText());
      
     
   
      
        data.add(this.Age1.getText());
      
        if (female.isSelected()) {
            data.add("Female");
        } else{
            data.add("Male");
  
        }
        data.add(bg.getSelectedItem().toString());
        data.add(this.wt.getText());
        
       

        return data;

    }
 public boolean isNumeric(String a) {
        return a.matches("-?\\d+(\\.\\d+)?");
    }

    public boolean isAlphabet(String name) {
        return name.matches("[a-zA-Z]+");
    }
    public boolean isValidData() {
        boolean result = true;
        if (this.First_Name1.getText().isEmpty()) {
           

            result = false;// TODO add your handling code here:
        }
        else if(!isAlphabet(this.First_Name1.getText())){
            JOptionPane.showMessageDialog(this, "Invalid first name", "Error", HEIGHT); // TODO add your handling code here            result = false;
        }
            else if (this.Last_Name1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the last Name", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        }else if(!isAlphabet(this.Last_Name1.getText())){
            JOptionPane.showMessageDialog(this, "Invalid last name", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        }
            else if (this.Address1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the address", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if(!isAlphabet(this.Address1.getText())){
            JOptionPane.showMessageDialog(this, "Invalid Address", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        }
            else if (this.Phone1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the Phone no", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if(!isNumeric(this.Phone1.getText())){
            JOptionPane.showMessageDialog(this, "Invalid Phone Number", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        }
            else if (this.Age1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the Age", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        }else if(!isNumeric(this.Age1.getText())){
            JOptionPane.showMessageDialog(this, "Invalid Age", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        }
            else if (!this.female.isSelected() && !this.male.isSelected() && !this.other.isCursorSet()) {
            JOptionPane.showMessageDialog(this, "Please Enter the gender", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        } else if (this.wt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter the weight ", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        }else if(!isNumeric(this.wt.getText())){
            JOptionPane.showMessageDialog(this, "Invalid weight", "Error", HEIGHT); // TODO add your handling code here:
            result = false;
        }
        else {
        }
        return result;

    }

    /**
     * @param args the command line arguments
     */
ButtonGroup bg1 = new ButtonGroup();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField Address1;
    private javax.swing.JTextPane Age1;
    private javax.swing.JLabel Blood_Group;
    private javax.swing.JLabel End_Time;
    private javax.swing.JLabel First_Name;
    private javax.swing.JTextField First_Name1;
    private javax.swing.JLabel Last_Name;
    private javax.swing.JTextField Last_Name1;
    private javax.swing.JTextField Phone1;
    private javax.swing.JLabel Phone_No;
    private javax.swing.JLabel Start_Time;
    private javax.swing.JComboBox<String> bg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton male;
    private javax.swing.JPanel other;
    private javax.swing.JTextField wt;
    // End of variables declaration//GEN-END:variables
}
